author: Peter Millard
name: pmill/github-trello
description: GitHub Action to attach GitHub branches to a Trello card
branding:
  icon: 'check-square'
  color: 'gray-dark'
inputs:
  trello-api-key:
    description: Trello API key, visit https://trello.com/app-key for key
    required: true
  trello-auth-token:
    description: Trello auth token, visit https://trello.com/app-key then click generate a token
    required: true
  trello-board-id:
    description: Trello board ID, visit a board then append .json to url to find id
    required: true
runs:
  using: node12
  main: dist/index.js
